version: "3.1"
services: 
  web:
    image: "node:latest"
    container_name: "web"
    ports:
      - "3000:3000"
    volumes:
      - './:/app'
      - '/app/node_modules'
    stdin_open: true
    working_dir: /app
    command: sh -c "npm install && npm start"